homeassistant:
  customize:
    person.trevor:
      entity_picture: /local/img/trevor.png
    device_tracker.iphone:
      entity_picture: /local/device_tracker.svg
    person.shelby:
      entity_picture: /local/img/shelby.png

    person.adam:
      entity_picture: /local/img/adam.png

person:
  - name: Trevor
    id: trevor
    device_trackers:
      - device_tracker.trevor_iphone_unifi
      - device_tracker.trevor_iphone #ios

  - name: Shelby
    id: shelby
    device_trackers:
      - device_tracker.shelby_iphone_unifi
      - device_tracker.shelbys_iphone #ios

  - name: Adam
    id: adam
    device_trackers:
      - device_tracker.adam_iphone_unifi

mqtt:
  sensor:
    - name: trevor_last_changed
      state_topic: homeassistant/persistence/trevor
      value_template: >
        {{ value | replace(' ', 'T') }}

    - name: shelby_last_changed
      state_topic: homeassistant/persistence/shelby
      value_template: >
        {{ value | replace(' ', 'T') }}

    - name: adam_last_changed
      state_topic: homeassistant/persistence/adam
      value_template: >
        {{ value | replace(' ', 'T') }}

automation:
  - alias: person_home
    id: '8423590985012'
    mode: parallel
    trigger:
      platform: state
      entity_id:
        - person.trevor
        - person.shelby
        - person.adam
      from:
        - home
        - not_home
      to:
        - home
        - not_home
    action:
      service: mqtt.publish
      data:
        topic_template: >
          homeassistant/persistence/{{ trigger.to_state.name | lower }}
        payload_template: >
          {{ now() }}
        retain: true
